import { EmployeeSummaryProfile } from '../interfaces/employee-profile.interface';

export const MOCK_EMPLOYEE_SUMMARIES: EmployeeSummaryProfile[] = [
  {
    id: '1',
    userId: 'u1',
    name: 'John Smith',
    ssn: '123-45-0001',
    workAuthorizationTitle: 'CITIZEN',
    phone: '555-0101',
    email: 'john.smith@example.com',
    username: 'jsmith',
  },
  {
    id: '2',
    userId: 'u2',
    name: 'Emily Johnson',
    ssn: '123-45-0002',
    workAuthorizationTitle: 'GREEN_CARD',
    phone: '555-0102',
    email: 'emily.johnson@example.com',
    username: 'ejohnson',
  },
  {
    id: '3',
    userId: 'u3',
    name: 'Michael Brown',
    ssn: '123-45-0003',
    workAuthorizationTitle: 'H1B',
    phone: '555-0103',
    email: 'michael.brown@example.com',
    username: 'mbrown',
  },
  {
    id: '4',
    userId: 'u4',
    name: 'Sarah Davis',
    ssn: '123-45-0004',
    workAuthorizationTitle: 'F1_CPT_OPT',
    phone: '555-0104',
    email: 'sarah.davis@example.com',
    username: 'sdavis',
  },
  {
    id: '5',
    userId: 'u5',
    name: 'David Wilson',
    ssn: '123-45-0005',
    workAuthorizationTitle: 'H4',
    phone: '555-0105',
    email: 'david.wilson@example.com',
    username: 'dwilson',
  },
  {
    id: '6',
    userId: 'u6',
    name: 'Jessica Martinez',
    ssn: '123-45-0006',
    workAuthorizationTitle: 'CITIZEN',
    phone: '555-0106',
    email: 'jessica.martinez@example.com',
    username: 'jmartinez',
  },
  {
    id: '7',
    userId: 'u7',
    name: 'Daniel Anderson',
    ssn: '123-45-0007',
    workAuthorizationTitle: 'L2',
    phone: '555-0107',
    email: 'daniel.anderson@example.com',
    username: 'danderson',
  },
  {
    id: '8',
    userId: 'u8',
    name: 'Laura Thomas',
    ssn: '123-45-0008',
    workAuthorizationTitle: 'GREEN_CARD',
    phone: '555-0108',
    email: 'laura.thomas@example.com',
    username: 'lthomas',
  },
  {
    id: '9',
    userId: 'u9',
    name: 'Kevin Taylor',
    ssn: '123-45-0009',
    workAuthorizationTitle: 'H1B',
    phone: '555-0109',
    email: 'kevin.taylor@example.com',
    username: 'ktaylor',
  },
  {
    id: '10',
    userId: 'u10',
    name: 'Amy Moore',
    ssn: '123-45-0010',
    workAuthorizationTitle: 'PENDING',
    phone: '555-0110',
    email: 'amy.moore@example.com',
    username: 'amoore',
  },
  {
    id: '11',
    userId: 'u11',
    name: 'Brian Jackson',
    ssn: '123-45-0011',
    workAuthorizationTitle: 'CITIZEN',
    phone: '555-0111',
    email: 'brian.jackson@example.com',
    username: 'bjackson',
  },
  {
    id: '12',
    userId: 'u12',
    name: 'Olivia White',
    ssn: '123-45-0012',
    workAuthorizationTitle: 'F1_CPT_OPT',
    phone: '555-0112',
    email: 'olivia.white@example.com',
    username: 'owhite',
  },
  {
    id: '13',
    userId: 'u13',
    name: 'James Harris',
    ssn: '123-45-0013',
    workAuthorizationTitle: 'OTHER',
    phone: '555-0113',
    email: 'james.harris@example.com',
    username: 'jharris',
  },
  {
    id: '14',
    userId: 'u14',
    name: 'Sophia Clark',
    ssn: '123-45-0014',
    workAuthorizationTitle: 'GREEN_CARD',
    phone: '555-0114',
    email: 'sophia.clark@example.com',
    username: 'sclark',
  },
  {
    id: '15',
    userId: 'u15',
    name: 'Andrew Lewis',
    ssn: '123-45-0015',
    workAuthorizationTitle: 'H1B',
    phone: '555-0115',
    email: 'andrew.lewis@example.com',
    username: 'alewis',
  },
  {
    id: '16',
    userId: 'u16',
    name: 'Megan Lee',
    ssn: '123-45-0016',
    workAuthorizationTitle: 'CITIZEN',
    phone: '555-0116',
    email: 'megan.lee@example.com',
    username: 'mlee',
  },
  {
    id: '17',
    userId: 'u17',
    name: 'Ryan Walker',
    ssn: '123-45-0017',
    workAuthorizationTitle: 'L2',
    phone: '555-0117',
    email: 'ryan.walker@example.com',
    username: 'rwalker',
  },
  {
    id: '18',
    userId: 'u18',
    name: 'Natalie Hall',
    ssn: '123-45-0018',
    workAuthorizationTitle: 'H4',
    phone: '555-0118',
    email: 'natalie.hall@example.com',
    username: 'nhall',
  },
  {
    id: '19',
    userId: 'u19',
    name: 'Christopher Allen',
    ssn: '123-45-0019',
    workAuthorizationTitle: 'CITIZEN',
    phone: '555-0119',
    email: 'chris.allen@example.com',
    username: 'callen',
  },
  {
    id: '20',
    userId: 'u20',
    name: 'Isabella Young',
    ssn: '123-45-0020',
    workAuthorizationTitle: 'PENDING',
    phone: '555-0120',
    email: 'isabella.young@example.com',
    username: 'iyoung',
  },
];
